(deftheme my-dark
  "Created 2022-05-10.")

(custom-theme-set-faces
 'my-dark
 '(default ((t (:family "Hack" :foundry "simp" :width normal :height 120 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#d4d4d4" :background "#1e1e1e" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#d4d4d4"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight normal :foreground "#4ec9b0"))))
 '(region ((t (:extend nil :background "#264f78"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:inherit (region)))))
 '(trailing-whitespace ((t (:background "#f16969"))))
 '(font-lock-builtin-face ((t (:foreground "#c586c0"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#6a9955"))))
 '(font-lock-constant-face ((t (:foreground "#569cd6"))))
 '(font-lock-doc-face ((t (:foreground "#ce9178"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:weight normal :foreground "#dcdcaa"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#569cd6"))))
 '(font-lock-negation-char-face ((t (:foreground "#569cd6"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#d7ba7d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d7ba7d"))))
 '(font-lock-string-face ((t (:foreground "#ce9178"))))
 '(font-lock-type-face ((t (:foreground "#4ec9b0"))))
 '(font-lock-variable-name-face ((t (:foreground "#9cdcfe"))))
 '(font-lock-warning-face ((t (:foreground "#f16969" :background "#252526"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#3794ff"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#fafafa"))))
 '(header-line ((t (:weight normal :foreground "#fafafa" :background "#333333"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:weight normal :foreground "#fafafa" :background "#8b008b"))))
 '(mode-line-buffer-id ((t (:weight normal :foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:foreground "#d4d4d4"))))
 '(mode-line-highlight ((t (:weight normal :box nil :foreground "#569cd6"))))
 '(mode-line-inactive ((t (:weight normal :foreground "#d4d4d4" :background "#005aa3"))))
 '(isearch ((t (:background "#613214"))))
 '(highlight ((t (:background "#3d3d3d"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "#613214"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'my-dark)
