;; -*- lexical-binding: t -*-

(straight-use-package 'window-purpose)
(require 'window-purpose)
(purpose-mode +1)

(add-to-list 'purpose-user-mode-purposes '(haskell-mode   . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(prog-mode   . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(text-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(fundamental-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(css-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(javascript-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(js2-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(typescript-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(web-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(dired-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(emacs-lisp-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(less-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(org-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(so-long-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(nxml-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(zip-archive-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(sql-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(archive-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(magit-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(vc-dir-mode . main-purpose))
(add-to-list 'purpose-user-mode-purposes '(magit-revision-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(diff-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(git-log-view-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(log-view-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(undo-tree-visualizer-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(help-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(haskell-compilation-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(compilation-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(rg-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(occur-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(eshell-mode . second-purpose))
(add-to-list 'purpose-user-mode-purposes '(grep-mode . second-purpose))

(add-to-list 'purpose-user-regexp-purposes '("\\*.*\\*" . other-purpose))
(add-to-list 'purpose-user-regexp-purposes '("\\*Flycheck.*" . build-purpose))
(add-to-list 'purpose-user-regexp-purposes '("\\*haskell-compilation\\*" . build-purpose))
(add-to-list 'purpose-user-regexp-purposes '("\\*Flymake.*" . build-purpose))
(add-to-list 'purpose-user-regexp-purposes '("\\*Find.*" . second-purpose))
(add-to-list 'purpose-user-regexp-purposes '("\\*Message.*" . second-purpose))
(add-to-list 'purpose-user-regexp-purposes '("\\*scratch\\*" . main-purpose))

(custom-set-variables
 `(purpose-use-default-configuration . nil)
 `(purpose-use-built-in-layouts . nil))

(purpose-compile-user-configuration)
(purpose-load-window-layout "start")

(provide 'my-layout2)
